[ENTITIES.ethan]
drawable = true
player = true

[ENTITIES.ethan.sprite]
path = "client/assets/images/champions/ethan/ethan.png"
size = [433, 577]
scale = [144.3, 192.3]
origin = [216, 577]
layer = 1

[ENTITIES.ethan.animation]
frames = [
    [[0, 0], 1, 0.4, false],
    [[0, 1], 1, 0.4, false],
    [[0, 2], 1, 0.4, false],
    [[0, 3], 1, 0.4, false],
    [[0, 4], 1, 0.4, false],
    [[0, 5], 1, 0.4, false],
    [[0, 6], 1, 0.4, false],
    [[0, 7], 1, 0.4, false],
    [[0, 8], 1, 0.4, false],
    [[0, 9], 1, 0.4, false],
    [[0, 10], 1, 0.4, false],
]
