[ENTITIES.ethan]
drawable = true
player = true
champion = true
target = true

[ENTITIES.ethan.team]
name = "blue"

[ENTITIES.ethan.velocity2]
x = 0
y = 0

[ENTITIES.ethan.sprite]
path = "client/assets/images/champions/ethan/ethan.png"
size = [433, 577]
scale = [144.3, 192.3]
origin = [216, 288]
layer = 1

[ENTITIES.ethan.animation]
frames = [
    # IDLE
    [[0, 0], 1, 0.4, false],
    [[0, 1], 1, 0.4, false],
    [[0, 2], 1, 0.4, false],
    [[0, 3], 1, 0.4, false],
    [[0, 4], 1, 0.4, false],

    # MOVEMENT
    [[0, 5], 1, 0.4, false],
    [[0, 6], 1, 0.4, false],
    [[0, 7], 1, 0.4, false],
    [[0, 8], 1, 0.4, false],
    [[0, 9], 1, 0.4, false],
    [[0, 10], 1, 0.4, false],
]

[ENTITIES.ethan.hitbox]
left = 0.0
top = 0.0
width = 144.3
height = 192.3

[ENTITIES.ethan.stat_pool]
ad = 10
ap = 0
atk_speed = 1.0
armor = 20
magic_resist = 20
mov_speed = 300

[ENTITIES.ethan.health]
amount = 200
max = 200
regen = 3

[ENTITIES.ethan.mana]
amount = 300
max = 300
regen = 3
