[ENTITIES.Gules]
drawable = true
player = true

[ENTITIES.Gules.sprite]
path = "client/assets/images/champions/Gules/Gules.png"
size = [387, 644]
scale = [144.3, 192.3]
origin = [193, 644]
layer = 1

[ENTITIES.Gules.animation]
frames = [
    # IDLE
    [[0, 0], 5, 0.4, true],

    # MOVEMENT
    [[0, 1], 5, 0.4, true],
    [[0, 2], 4, 0.4, true],
    [[0, 3], 4, 0.4, true],
    [[0, 4], 4, 0.4, true],
    [[0, 5], 4, 0.4, true],

    # AUTO ATTACK
    [[0, 6], 5, 0.4, false],
    [[0, 7], 5, 0.4, false],
    [[0, 8], 4, 0.4, false],
    [[0, 9], 5, 0.4, false],
    [[0, 10], 4, 0.4, false],

    # SPELL 1
    [[0, 11], 5, 0.4, false],
    [[0, 12], 4, 0.4, false],
    [[0, 13], 4, 0.4, false],
    [[0, 14], 5, 0.4, false],
    [[0, 15], 5, 0.4, false],

    # SPELL 2
    [[0, 16], 4, 0.4, false],
    [[0, 17], 4, 0.4, false],
    [[0, 18], 4, 0.4, false],
    [[0, 19], 4, 0.4, false],
    [[0, 20], 4, 0.4, false],

    # DEATH
    [[0, 21], 5, 0.4, false],
]
