[ENTITIES.Croly]
position2 = true
target = true

[ENTITIES.Croly.champion]
name = "Croly"

[ENTITIES.Croly.attack]
name = "croly_aa"
auto = false

[ENTITIES.Croly.circle_hitbox]
radius = 20
pushback = true

[ENTITIES.Croly.team]
name = ""

[ENTITIES.Croly.velocity2]
x = 0
y = 0

[ENTITIES.Croly.health]
amount = 600
max = 600
regen = 3

[ENTITIES.Croly.mana]
amount = 300
max = 300
regen = 3

[ENTITIES.Croly.xp]
amount = 0

[ENTITIES.Croly.hitbox]
left = 0.0
top = 0.0
width = 144.3
height = 192.3

[ENTITIES.Croly.stat_pool]
ad = 67
ap = 0
atk_speed = 1.5
atk_range = 350
cdr = 0
armor = 34
magic_resist = 25
mov_speed = 1000

[ENTITIES.Croly.spells]
indexs = [0, 0]

# --------------------

[ENTITIES.croly_aa]
position2 = true
velocity2 = true
target = true

[ENTITIES.croly_aa.team]
name = ""

[ENTITIES.croly_aa.spell]
name = "croly_aa"
base = 0
damage_type = 0
ratios = [1.0, 0.0]
cooldown = 2.0
cast_time = 1.0
target = 0
mana_cost = 0
speed = 500
