[ENTITIES.ethan]
position2 = true
champion = true

[ENTITIES.ethan.velocity2]
x = 0
y = 0

[ENTITIES.ethan.stat_pool]
ad = 67
ap = 0
atk_speed = 1.5
atk_range = 200
cdr = 0
armor = 34
magic_resist = 25
mov_speed = 350

[ENTITIES.ethan.casting]
spell1 = [
    "name",
    50, # Base Damage
    0, # DamageType 0 = PHYSIC 1 = MAGICAL
    5.0, # Cooldown
    0.2, # Cast time
    0, # 0 NONE / 1 ALLY / 2 ENEMY / 3 MONSTER
    [
        100, # Ratio PHYSIC
        0 # Ratio MAGIC
    ],
    [ # Enitiées à créer
        "balle"
    ],
]
spell2 = [
    "name",
    50, # Base Damage
    0, # DamageType 0 = PHYSIC 1 = MAGICAL
    5.0, # Cooldown
    0.2, # Cast time
    0, # 0 NONE / 1 ALLY / 2 ENEMY / 3 MONSTER
    [
        20, # Ratio PHYSIC
        100 # Ratio MAGIC
    ],
    [ # Enitiées à créer
        "balle"
    ]
]

[ENTITIES.balle]
position2 = true

[ENTITIES.balle.velocity2]
x = 0
y = 0

[ENTITIES.balle.hitbox]
top = 0
left = 0
width = 0
height = 0

# [ENTITIES.balle.stat_pool] created when spell is launched

# [ENTITIES.balle.spell] created when spell is launched
# entity = 0 # Entity with casting (ethan)
# spell = 1 # or 2
