[ENTITIES.Goatier]
position2 = true
target = true

[ENTITIES.Goatier.champion]
name = "Goatier"

[ENTITIES.Goatier.attack]
name = "goatier_aa"
auto = false

[ENTITIES.Goatier.circle_hitbox]
radius = 20
pushback = true

[ENTITIES.Goatier.team]
name = ""

[ENTITIES.Goatier.velocity2]
x = 0
y = 0

[ENTITIES.Goatier.health]
amount = 500
max = 500
regen = 3

[ENTITIES.Goatier.mana]
amount = 420
max = 420
regen = 5

[ENTITIES.Goatier.xp]
amount = 0

[ENTITIES.Goatier.hitbox]
left = 0.0
top = 0.0
width = 144.3
height = 192.3

[ENTITIES.Goatier.stat_pool]
ad = 58
ap = 0
atk_speed = 1.6
atk_range = 350
cdr = 0
armor = 34
magic_resist = 25
mov_speed = 330

[ENTITIES.Goatier.spells]
indexs = [3, 4]

# --------------------

[ENTITIES.goatier_aa]
position2 = true
velocity2 = true
target = true

[ENTITIES.goatier_aa.team]
name = ""

[ENTITIES.goatier_aa.spell]
name = "goatier_aa"
base = 0
damage_type = 0
ratios = [1.0, 0.0]
cast_time = 1.0
target = 2
speed = 450

# --------------------

[ENTITIES.goatier_spell1]
position2 = true
velocity2 = true
target = true

[ENTITIES.goatier_spell1.team]
name = ""

[ENTITIES.goatier_spell1.spell]
name = "goatier_spell1"
base = 100
damage_type = 1
ratios = [0.0, 0.6]
cooldown = 6.0
cast_time = 1.0
target = 0
mana_cost = 40
speed = 800
range = 800
aoe_radius = 120.0
persistent = false

[ENTITIES.goatier_spell1.hitbox]
top = 0
left = 0
width = 50
height = 50

# --------------------

[ENTITIES.goatier_spell2]
position2 = true
target = true

[ENTITIES.goatier_spell2.team]
name = ""

[ENTITIES.goatier_spell2.spell]
name = "goatier_spell2"
cooldown = 10.0
target = 0
mana_cost = 80
range = 600
