[ENTITIES.Gules]
position2 = true
target = true
movable = true

[ENTITIES.Gules.champion]
name = "Gules"

[ENTITIES.Gules.attack]
name = "gules_aa"
auto = false

[ENTITIES.Gules.circle_hitbox]
radius = 20
pushback = true

[ENTITIES.Gules.team]
name = ""

[ENTITIES.Gules.velocity2]
x = 0
y = 0

[ENTITIES.Gules.health]
amount = 600
max = 600
regen = 3

[ENTITIES.Gules.mana]
amount = 500
max = 500
regen = 3

[ENTITIES.Gules.xp]
amount = 0

[ENTITIES.Gules.hitbox]
left = 0.0
top = 0.0
width = 258
height = 430

[ENTITIES.Gules.stat_pool]
ad = 55
ap = 0
atk_speed = 1.4
atk_range = 300
cdr = 0
armor = 34
magic_resist = 25
mov_speed = 320

[ENTITIES.Gules.spells]
indexs = [1, 2]

# --------------------

[ENTITIES.gules_aa]
position2 = true
velocity2 = true
target = true

[ENTITIES.gules_aa.team]
name = ""

[ENTITIES.gules_aa.spell]
name = "gules_aa"
base = 0
damage_type = 0
ratios = [1.0, 0.0]
cast_time = 1.0
target = 0
speed = 500

# --------------------

[ENTITIES.gules_ball]
position2 = true
target = true

[ENTITIES.gules_ball.team]
name = ""

[ENTITIES.gules_ball.spell]
name = "gules1"
base = 100
damage_type = 1
ratios = [0.0, 0.4]
cooldown = 4.0
target = 0
mana_cost = 40
speed = 700
range = 600
aoe_radius = 100.0
persistent = true

[ENTITIES.gules_ball.velocity2]
x = 0
y = 0

[ENTITIES.gules_ball.hitbox]
top = 0
left = 0
width = 50
height = 50
