[ENTITIES.tower_blue]
drawable = true
position2 = true
auto_attack = true

[ENTITIES.tower_blue.team]
name = "red"

[ENTITIES.tower_blue.sprite]
path = "client/assets/images/buildings/tower_blue_top.png"
size = [514, 1133]
scale = [171, 378]
origin = [171, 378]
layer = 10

[ENTITIES.tower_blue.stat_pool]
ad = 10
ap = 0
atk_speed = 1.0
armor = 20
atk_range = 200
magic_resist = 20
mov_speed = 300

[ENTITIES.tower_blue.health]
health = 1
health_max = 200
health_regen = 3

[ENTITIES.tower_blue.mana]
mana = 300
mana_max = 300
mana_regen = 3

[ENTITIES.tower_projectiles_blue]
drawable = true
position2 = true

[ENTITIES.tower_projectiles_blue.team]
name = "red"

[ENTITIES.tower_projectiles_blue.velocity2]
x = 0
y = 0

[ENTITIES.tower_projectiles_blue.stat_pool]
ad = 10
ap = 0

[ENTITIES.tower_projectiles_blue.hitbox]
left = 0.0
top = 0.0
width = 16.0
height = 16.0

[ENTITIES.tower_projectiles_blue.auto_track]
speed = 300

[ENTITIES.tower_projectiles_blue.sprite]
path = "client/assets/images/buildings/tower_projectile.png"
size = [16, 16]
origin = [8, 8]
layer = 10

[ENTITIES.tower_projectiles_blue.animation]
frames = [
    [[0, 0], 3, 0.4, true]
]
