[ENTITIES.tower_red]
drawable = true
position2 = true
auto_attack = true

[ENTITIES.tower_red.team]
name = "red"

[ENTITIES.tower_red.sprite]
path = "client/assets/images/buildings/tower_red_top.png"
size = [575, 1459]
scale = [171, 378]
origin = [192, 486]
layer = 10

[ENTITIES.tower_red.stat_pool]
ad = 10
ap = 0
atk_speed = 1.0
armor = 20
atk_range = 200
magic_resist = 20
mov_speed = 300

[ENTITIES.tower_red.health]
health = 1
health_max = 200
health_regen = 3

[ENTITIES.tower_red.mana]
mana = 300
mana_max = 300
mana_regen = 3

[ENTITIES.tower_projectiles_red]
drawable = true
position2 = true

[ENTITIES.tower_projectiles_red.team]
name = "red"

[ENTITIES.tower_projectiles_red.velocity2]
x = 0
y = 0

[ENTITIES.tower_projectiles_red.stat_pool]
ad = 10
ap = 0

[ENTITIES.tower_projectiles_red.on_death]
entity = "tower_projectiles_explosion"


[ENTITIES.tower_projectiles_explosion]
drawable = true
position2 = true

    [ENTITIES.tower_projectiles_explosion.sprite]
    path = "client/assets/images/buildings/boom.png"
    # size = [16, 16]
    # center = true
    size = [128, 128]
    scale = [256, 256]
    origin = [64, 64]
    layer = 10

    [ENTITIES.tower_projectiles_explosion.animation]
    frames = [
        [[0, 0], 10, 0.2, false]
    ]

    [ENTITIES.tower_projectiles_explosion.timeout]
    duration = 2.0

    [ENTITIES.tower_projectiles_explosion.sound]
    path = "client/assets/audio/boom.mp3"
    play = true

[ENTITIES.tower_projectiles_red.hitbox]
left = 0.0
top = 0.0
width = 16.0
height = 16.0

[ENTITIES.tower_projectiles_red.auto_track]
speed = 300

[ENTITIES.tower_projectiles_red.sprite]
path = "client/assets/images/buildings/tower_projectile.png"
size = [16, 16]
origin = [8, 8]
layer = 10

[ENTITIES.tower_projectiles_red.animation]
frames = [
    [[0, 0], 3, 0.4, true]
]
