[ENTITIES.tower]
drawable = true
position2 = true
auto_attack = true

[ENTITIES.tower.team]
name = "red"

[ENTITIES.tower.sprite]
path = "client/assets/images/buildings/tower.png"
size = [401, 622]
scale = [200, 311]
origin = [200, 311]
layer = 1

[ENTITIES.tower.stat_pool]
ad = 10
ap = 0
atk_speed = 1.0
armor = 20
magic_resist = 20
mov_speed = 300

[ENTITIES.tower.health]
health = 1
health_max = 200
health_regen = 3

[ENTITIES.tower.mana]
mana = 300
mana_max = 300
mana_regen = 3

[ENTITIES.tower_projectiles]
drawable = true
position2 = true

[ENTITIES.tower_projectiles.velocity2]
x = 0
y = 0

[ENTITIES.tower_projectiles.auto_track]
speed = 300

[ENTITIES.tower_projectiles.sprite]
path = "client/assets/images/buildings/tower_projectile.png"
size = [16, 16]
origin = [8, 8]
layer = 1

[ENTITIES.tower_projectiles.animation]
frames = [
    [[0, 0], 3, 0.4, true]
]
