[ENTITIES.zone_left_enemy]
drawable = true
position2 = true

# [ENTITIES.zone_left_enemy.proc]
# radius = 200

[ENTITIES.zone_left_enemy.sprite]
path = "client/assets/images/buildings/red_circle.png"
size = [311, 200]
scale = [400, 400]
origin = [156, 100]
layer = 10
