[ENTITIES.play_button]
drawable = true
position2 = true
clickable = true

    [ENTITIES.play_button.sprite]
    path = "client/assets/images/ui/buttons/panel-transparent-center-005.png"
    size = [96, 96]
    scale = [100, 30]
    layer = 1

    [ENTITIES.play_button.hitbox]
    top = 0
    left = 0
    width = 100
    height = 20
