[ENTITIES.ethan]
drawable = true
position2 = true
player = true
champion = true
directed = true

[ENTITIES.ethan.velocity2]
x = 0
y = 0

[ENTITIES.ethan.sprite]
path = "assets/images/champions/ethan/ethan.png"
size = [433, 577]
scale = [144.3, 192.3]
origin = [216, 577]
layer = 1

[ENTITIES.ethan.animation]
frames = [
    [[0, 0], 1, 0.4, false],
    [[0, 1], 1, 0.4, false],
    [[0, 2], 1, 0.4, false],
    [[0, 3], 1, 0.4, false],
    [[0, 4], 1, 0.4, false],
    [[0, 5], 1, 0.4, false],
    [[0, 6], 1, 0.4, false],
    [[0, 7], 1, 0.4, false],
    [[0, 8], 1, 0.4, false],
    [[0, 9], 1, 0.4, false],
    [[0, 10], 1, 0.4, false],
]

[ENTITIES.ethan.stat_pool]
ad = 10
ap = 0
atk_speed = 1.0
armor = 20
magic_resist = 20
mov_speed = 300
