[ENTITIES.tower]
position2 = true

[ENTITIES.tower.team]
name = ""

[ENTITIES.tower.health]
amount = 5000
delay = 0

[ENTITIES.tower.building]
name = "tower"

[ENTITIES.tower_projectiles]
position2 = true

[ENTITIES.tower_projectiles.velocity2]
x = 0
y = 0

[ENTITIES.tower_projectiles.auto_track]
speed = 300
