[ENTITIES.sl_return_button]
drawable = true
position2 = true
clickable = true
hoverable = true
button = true

    [ENTITIES.sl_return_button.sprite]
    path = "client/assets/images/ui/buttons/button.png"
    size = [30, 31]
    scale = [80, 40]
    layer = 11

    [ENTITIES.sl_return_button.hitbox]
    top = 10
    left = 0
    width = 80
    height = 40

    [ENTITIES.sl_return_button.animation]
    frames = [
        # DEFAULT
        [[3, 0], 1, 0.0, false],
        # CLICKED
        [[1, 0], 1, 0.0, false],
        # HOVER
        [[0, 0], 1, 0.0, false],
    ]

[ENTITIES.create_lobby]
drawable = true
position2 = true
clickable = true
hoverable = true
button = true

    [ENTITIES.create_lobby.sprite]
    path = "client/assets/images/ui/buttons/button.png"
    size = [30, 31]
    scale = [150, 80]
    layer = 11

    [ENTITIES.create_lobby.hitbox]
    top = 10
    left = 0
    width = 150
    height = 80

    [ENTITIES.create_lobby.animation]
    frames = [
        # DEFAULT
        [[3, 0], 1, 0.0, false],
        # CLICKED
        [[1, 0], 1, 0.0, false],
        # HOVER
        [[0, 0], 1, 0.0, false],
    ]
