[ENTITIES.lobby_return_button]
drawable = true
position2 = true
clickable = true
hoverable = true
button = true

    [ENTITIES.lobby_return_button.sprite]
    path = "client/assets/images/ui/buttons/button.png"
    size = [30, 31]
    scale = [80, 40]
    layer = 11

    [ENTITIES.lobby_return_button.hitbox]
    top = 0
    left = 0
    width = 80
    height = 40

    [ENTITIES.lobby_return_button.animation]
    frames = [
        # DEFAULT
        [[3, 0], 1, 0.0, false],
        # CLICKED
        [[1, 0], 1, 0.0, false],
        # HOVER
        [[0, 0], 1, 0.0, false],
    ]

    [ENTITIES.lobby_return_button.text]
    string = ""
    font = "client/assets/images/ui/main_font.otf"
    offset = [40, 12]
    size = 20
    center = true
    color = [255, 255, 255, 255]

[ENTITIES.create_lobby]
drawable = true
position2 = true
clickable = true
hoverable = true
button = true

    [ENTITIES.create_lobby.sprite]
    path = "client/assets/images/ui/buttons/button.png"
    size = [30, 31]
    scale = [380, 100]
    layer = 11

    [ENTITIES.create_lobby.hitbox]
    top = 0
    left = 0
    width = 380
    height = 100

    [ENTITIES.create_lobby.animation]
    frames = [
        # DEFAULT
        [[3, 0], 1, 0.0, false],
        # CLICKED
        [[1, 0], 1, 0.0, false],
        # HOVER
        [[0, 0], 1, 0.0, false],
    ]

    [ENTITIES.create_lobby.text]
    string = ""
    font = "client/assets/images/ui/main_font.otf"
    offset = [190, 45]
    size = 40
    center = true
    color = [255, 255, 255, 255]

[ENTITIES.launch_game]
drawable = true
position2 = true
clickable = true
hoverable = true
button = true

    [ENTITIES.launch_game.sprite]
    path = "client/assets/images/ui/buttons/button.png"
    size = [30, 31]
    scale = [200, 50]
    layer = 11

    [ENTITIES.launch_game.hitbox]
    top = 0
    left = 0
    width = 200
    height = 50

    [ENTITIES.launch_game.animation]
    frames = [
        # DEFAULT
        [[3, 0], 1, 0.0, false],
        # CLICKED
        [[1, 0], 1, 0.0, false],
        # HOVER
        [[0, 0], 1, 0.0, false],
    ]

    [ENTITIES.launch_game.text]
    string = "START"
    font = "client/assets/images/ui/main_font.otf"
    offset = [100, 20]
    size = 20
    center = true
    color = [255, 255, 255, 255]

[ENTITIES.select_blue]
drawable = true
position2 = true
clickable = true
hoverable = true
button = true

    [ENTITIES.select_blue.sprite]
    path = "client/assets/images/ui/buttons/button.png"
    size = [30, 31]
    scale = [200, 50]
    layer = 11

    [ENTITIES.select_blue.hitbox]
    top = 0
    left = 0
    width = 200
    height = 50

    [ENTITIES.select_blue.animation]
    frames = [
        # DEFAULT
        [[3, 0], 1, 0.0, false],
        # CLICKED
        [[1, 0], 1, 0.0, false],
        # HOVER
        [[0, 0], 1, 0.0, false],
    ]

    [ENTITIES.select_blue.text]
    string = "BLUE"
    font = "client/assets/images/ui/main_font.otf"
    offset = [100, 20]
    size = 20
    center = true
    color = [255, 255, 255, 255]

[ENTITIES.select_red]
drawable = true
position2 = true
clickable = true
hoverable = true
button = true

    [ENTITIES.select_red.sprite]
    path = "client/assets/images/ui/buttons/button.png"
    size = [30, 31]
    scale = [200, 50]
    layer = 11

    [ENTITIES.select_red.hitbox]
    top = 0
    left = 0
    width = 200
    height = 50

    [ENTITIES.select_red.animation]
    frames = [
        # DEFAULT
        [[3, 0], 1, 0.0, false],
        # CLICKED
        [[1, 0], 1, 0.0, false],
        # HOVER
        [[0, 0], 1, 0.0, false],
    ]

    [ENTITIES.select_red.text]
    string = "RED"
    font = "client/assets/images/ui/main_font.otf"
    offset = [100, 20]
    size = 20
    center = true
    color = [255, 255, 255, 255]

[ENTITIES.lobby_list]
drawable = true
position2 = true
clickable = true
hoverable = true
button = true

    [ENTITIES.lobby_list.sprite]
    path = "client/assets/images/ui/buttons/button.png"
    size = [30, 31]
    scale = [200, 50]
    layer = 11

    [ENTITIES.lobby_list.hitbox]
    top = 0
    left = 0
    width = 200
    height = 50

    [ENTITIES.lobby_list.animation]
    frames = [
        # DEFAULT
        [[3, 0], 1, 0.0, false],
        # CLICKED
        [[1, 0], 1, 0.0, false],
        # HOVER
        [[0, 0], 1, 0.0, false],
    ]

    [ENTITIES.lobby_list.text]
    string = ""
    font = "client/assets/images/ui/main_font.otf"
    offset = [100, 20]
    size = 20
    center = true
    color = [255, 255, 255, 255]
