[ENTITIES.range_blue_creap_down]
drawable = true

[ENTITIES.range_blue_creap_down.sprite]
path = "client/assets/images/minions/range_blue.png"
size = [387, 644]
scale = [77, 128]
origin = [193.5, 322]
layer = 10

[ENTITIES.range_blue_creap_down.animation]
frames = [
    #IDLE
    [[0, 0], 4, 0.4, true],

    #MOUVEMENT
    [[0, 1], 4, 0.2, true],
    [[0, 2], 4, 0.2, true],
    [[0, 3], 4, 0.2, true],
    [[0, 4], 4, 0.2, true],
    [[0, 5], 4, 0.2, true],

    # AUTO ATTACK
    [[0, 6], 5, 0.2, false],
    [[0, 7], 5, 0.2, false],
    [[0, 8], 4, 0.2, false],
    [[0, 9], 5, 0.2, false],
    [[0, 10], 4, 0.2, false],

    # SPELL 1
    [[0, 11], 5, 0.2, false],
    [[0, 12], 4, 0.2, false],
    [[0, 13], 4, 0.2, false],
    [[0, 14], 5, 0.2, false],
    [[0, 15], 5, 0.2, false],

    # SPELL 2
    [[0, 16], 4, 0.2, false],
    [[0, 17], 4, 0.2, false],
    [[0, 18], 4, 0.2, false],
    [[0, 19], 4, 0.2, false],
    [[0, 20], 4, 0.2, false],

    # DEATH
    [[0, 21], 5, 0.4, false],
    ]
