[ENTITIES.range_red_creap]
drawable = true
position2 = true
target = true
auto_attack = true

[ENTITIES.range_red_creap.velocity2]
x = 0
y = 0

[ENTITIES.range_red_creap.minions]
name = "range_red"

[ENTITIES.range_red_creap.sprite]
path = "client/assets/images/minions/range_red.png"
size = [387, 644]
scale = [77, 128]
origin = [193.5, 322]
layer = 11

[ENTITIES.range_red_creap.team]
team = "red"

[ENTITIES.range_red_creap.health]
amount = 1
max = 200
regen = 3

[ENTITIES.range_red_creap.mana]
amount = 1
max = 200
regen = 3

[ENTITIES.range_red_creap.stat_pool]
ad = 3
ap = 0
atk_speed = 3
atk_range = 50
cdr = 0
armor = 34
magic_resist = 25
mov_speed = 150

[ENTITIES.range_red_creap.animation]
frames = [
    #IDLE
    [[0, 0], 4, 0.4, true],

    #MOUVEMENT
    [[0, 1], 4, 0.2, true],
    [[0, 2], 4, 0.2, true],
    [[0, 3], 4, 0.2, true],
    [[0, 4], 4, 0.2, true],
    [[0, 5], 4, 0.2, true],

    # AUTO ATTACK
    [[0, 6], 5, 0.2, false],
    [[0, 7], 5, 0.2, false],
    [[0, 8], 4, 0.2, false],
    [[0, 9], 5, 0.2, false],
    [[0, 10], 4, 0.2, false],

    # SPELL 1
    [[0, 11], 5, 0.2, false],
    [[0, 12], 4, 0.2, false],
    [[0, 13], 4, 0.2, false],
    [[0, 14], 5, 0.2, false],
    [[0, 15], 5, 0.2, false],

    # SPELL 2
    [[0, 16], 4, 0.2, false],
    [[0, 17], 4, 0.2, false],
    [[0, 18], 4, 0.2, false],
    [[0, 19], 4, 0.2, false],
    [[0, 20], 4, 0.2, false],

    # DEATH
    [[0, 21], 5, 0.4, false],
    ]

[ENTITIES.range_red_creap.minion_route]
direction1 = [2000, 700]
direction2 = [4096, 1480]
direction3 = [6192, 700]
direction4 = [6792, 1000]

[ENTITIES.range_red_creap.auto_track]
speed = 300
