[ENTITIES.range_blue_creap_top]
position2 = true
target = true
clickable = true

[ENTITIES.range_blue_creap_top.velocity2]
x = 0
y = 0

[ENTITIES.range_blue_creap_top.team]
name = "blue"

[ENTITIES.range_blue_creap_top.minions]
name = "range_blue"

[ENTITIES.range_blue_creap_top.health]
amount = 1
max = 200
regen = 3

[ENTITIES.range_blue_creap_top.mana]
amount = 1
max = 200
regen = 3

[ENTITIES.range_blue_creap_top.stat_pool]
ad = 3
ap = 0
atk_speed = 3
atk_range = 50
cdr = 0
armor = 34
magic_resist = 25
mov_speed = 200

[ENTITIES.range_blue_creap_top.attack]
name = "tower_projectile"
auto = true

[ENTITIES.range_blue_creap_top.minion_route]
direction1 = [2000, 700]
direction2 = [4096, 1480]
direction3 = [6192, 700]
direction4 = [6792, 1000]
